import { gql } from "@apollo/client";

export const GET_ALL_INVENTORY_ITEMS_QUERY = gql`
  query GetAllInventoryItems($storeid: Int!) {
    getAllInventoryItems(storeid: $storeid) {
      itemid
      itembarcodeid
      itemcode
      itemdescription
      detaileditemdescription
      itemunit
      itemsellprice
      itemminimumsellprice
      supplierbarcodeid
      supplieritemcode
      modelno
      manufacturer
      itemtaxable
      itemdiscount
      itempurchaseprice
      itemaveragecost
      trackinventory
      itemcategoryid
      subcategoryid
      itemstatus
      itemimagepath
      itemremarks
      supplierid
      itemtagpricecode
      itemtagprice
      adjupdatebyid
      adjdate
      adjremarks
      ringgoldweight
      itemmetalpremiume
      itemtype
      itemsetpcs
      itemlength
      itemsize
      itemcolor
      itemlabor
      itemmetal
      itemmetalpercent
      itempremium
      broakerage
      broakeragepercent
      subtituteitem
      itemalertwarning
      itemwarningmessage
      tag1
      tag2
      tag3
      tag4
      tag5
      tag6
      tag7
      tag0
      tag9
      tag10
      dshape
      dlab
      dcerno
      dcarat
      ddiameter
      dcolor
      dclarity
      dflorence
      dpolarity
      ddepth
      dtable
      dpolish
      dsymmetry
      dcrownheight
      dcrownangle
      dpavillionheight
      dpavillionangle
      dmesurement
      dsize
      dquality
      dstockno
      dvendorshortname
      dbatchno
      drapprice
      dcost
      dsaleprice
      dpricecode
      ddatepurchase
      dlastsolddate
      dlastsoldprice
      dincludeininventory
      dpcs
      dqty
      createddate
      createdby
      lastmodifieddate
    }
  }
`;
