export type CustomerSalesSummary = {
  customerid: number;
  custcompanyname: string;
  year: number;
  invoice_count: number;
  total_sales: number;
  total_balance_due: number;
  total_profit: number;
  jan: number;
  feb: number;
  mar: number;
  apr: number;
  may: number;
  jun: number;
  jul: number;
  aug: number;
  sep: number;
  oct: number;
  nov: number;
  dec: number;
  warehousename: string;
  warehouseid: number;
  outletid: number;
};

export type MonthlyPaymentsPivotSummary = {
  year: number;
  month_display: string;

  monthly_payment: number;
  monthly_count: number;

  jan_total: number;
  feb_total: number;
  mar_total: number;
  apr_total: number;
  may_total: number;
  jun_total: number;
  jul_total: number;
  aug_total: number;
  sep_total: number;
  oct_total: number;
  nov_total: number;
  dec_total: number;

  payment_mode_totals: any;

  warehousename: string;
  warehouseid: number;
  outletid: number;
};

export type SupplierSalesPurchaseSummary = {
  supplier: string;
  year: number;
  total_purchase: number;
  total_sales: number;
  jan: number;
  feb: number;
  mar: number;
  apr: number;
  may: number;
  jun: number;
  jul: number;
  aug: number;
  sep: number;
  oct: number;
  nov: number;
  dec: number;
  warehousename: string;
  supplierid: number;
  warehouseid: number;
  outletid: number;
};

export type SupplierPurchaseSummary = {
  supplier: string;
  year: number;
  total_purchases: number;
  total_purchase_amount: number;
  total_amount_paid: number;
  total_balance_due: number;
  jan: number;
  feb: number;
  mar: number;
  apr: number;
  may: number;
  jun: number;
  jul: number;
  aug: number;
  sep: number;
  oct: number;
  nov: number;
  dec: number;
  warehousename: string;
  supplierid: number;
  warehouseid: number;
  outletid: number;
};

export type WarehouseSalesSummary = {
  warehousename: string;
  year: number;
  total_sales: number;
  total_cost: number;
  total_profit: number;
  profit_margin_percent: number;
  jan: number;
  feb: number;
  mar: number;
  apr: number;
  may: number;
  jun: number;
  jul: number;
  aug: number;
  sep: number;
  oct: number;
  nov: number;
  dec: number;
  warehouseid: number;
  outletid: number;
};

export type WarehouseYearlySummary = {
  warehousename: string;
  year: number;
  total_sales: number;
  total_cost: number;
  total_profit: number;
  profit_margin_percent: number;
  jan: number;
  feb: number;
  mar: number;
  apr: number;
  may: number;
  jun: number;
  jul: number;
  aug: number;
  sep: number;
  oct: number;
  nov: number;
  dec: number;
  warehouseid: number;
  outletid: number;
};

export type InvoiceSummary = {
  invoicenumber: string;
  customerid: string;
  custcompanyname: string;
  saledate: string;
  salemodename: string;
  totalamount: number;
  discountamount: number;
  subtotal: number;
  salestax: number;
  shipping: number;
  netamount: number;
  amountreceived: number;
  balancedue: number;
  taxablesale: number;
  nontaxablesale: number;
  totalcost: number;
  profit: number;
  profit_margin_percent: number;
  statusname: string;
  termsname: string;
  warehousename: string;
  warehouseid: number;
  outletid: number;
};

export type InvoiceItem = {
  invoiceitemid: number;
  invoicenumber: number;
  itemcode: string;
  itemdescription: string;
  itemquantity: number;
  unitprice: number;
  extendedprice: number;
  itemcost: number;
  totalcost: number;
  profit: number;
  profit_percent: number;
  itemid: string;
  warehouseid: number;
};

export type CategorySalesSummary = {
  categoryname: string;
  subcategoryname: string;
  year: number;
  total_quantity: number;
  total_sales: number;
  total_cost: number;
  total_profit: number;
  profit_margin_percent: number;
  jan: number;
  feb: number;
  mar: number;
  apr: number;
  may: number;
  jun: number;
  jul: number;
  aug: number;
  sep: number;
  oct: number;
  nov: number;
  dec: number;
  warehousename: string;
  warehouseid: number;
  outletid: number;
};

export type EmployeeYearlySalesSummary = {
  employeename: string;
  year: number;
  total_sales: number;
  total_cost: number;
  total_profit: number;
  profit_margin_percent: number;
  jan: number;
  feb: number;
  mar: number;
  apr: number;
  may: number;
  jun: number;
  jul: number;
  aug: number;
  sep: number;
  oct: number;
  nov: number;
  dec: number;
  warehousename: string;
  warehouseid: number;
  outletid: number;
};

export type DailySalesSummary = {
  year: number;
  month_display: string;
  monthly_total_sales: number;
  day_01: number;
  day_02: number;
  day_03: number;
  day_04: number;
  day_05: number;
  day_06: number;
  day_07: number;
  day_08: number;
  day_09: number;
  day_10: number;
  day_11: number;
  day_12: number;
  day_13: number;
  day_14: number;
  day_15: number;
  day_16: number;
  day_17: number;
  day_18: number;
  day_19: number;
  day_20: number;
  day_21: number;
  day_22: number;
  day_23: number;
  day_24: number;
  day_25: number;
  day_26: number;
  day_27: number;
  day_28: number;
  day_29: number;
  day_30: number;
  day_31: number;
  warehousename: string;
  warehouseid: number;
  outletid: number;
};

export type MonthlyPaymentSummary = {
  year: number;
  month_display: string;

  monthly_payment: number;
  monthly_count: number;

  day_01: number;
  day_02: number;
  day_03: number;
  day_04: number;
  day_05: number;
  day_06: number;
  day_07: number;
  day_08: number;
  day_09: number;
  day_10: number;
  day_11: number;
  day_12: number;
  day_13: number;
  day_14: number;
  day_15: number;
  day_16: number;
  day_17: number;
  day_18: number;
  day_19: number;
  day_20: number;
  day_21: number;
  day_22: number;
  day_23: number;
  day_24: number;
  day_25: number;
  day_26: number;
  day_27: number;
  day_28: number;
  day_29: number;
  day_30: number;
  day_31: number;

  payment_mode_totals: any;

  warehousename: string;
  warehouseid: number;
  outletid: number;
};
