import { ColDef, ICellRendererParams } from "ag-grid-community";
import { currencyFormattedCellRenderer } from "@/components/ui/products/list/columnDef";
import { MonthlyPaymentSummary } from "@/types/reports";

export const dailyPaymentsReportColumnDefs: ColDef<MonthlyPaymentSummary>[] = [
  {
    headerName: "Year",
    field: "year",
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Month",
    field: "month_display",
    filter: "agTextColumnFilter",
    hide: false,
  },
  {
    headerName: "Monthly Payment",
    field: "monthly_payment",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Monthly Count",
    field: "monthly_count",
    filter: "agNumberColumnFilter",
    hide: true,
  },
  {
    headerName: "01",
    field: "day_01",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "02",
    field: "day_02",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "03",
    field: "day_03",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "04",
    field: "day_04",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "05",
    field: "day_05",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "06",
    field: "day_06",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "07",
    field: "day_07",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "08",
    field: "day_08",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "09",
    field: "day_09",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "10",
    field: "day_10",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "11",
    field: "day_11",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "12",
    field: "day_12",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "13",
    field: "day_13",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "14",
    field: "day_14",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "15",
    field: "day_15",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "16",
    field: "day_16",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "17",
    field: "day_17",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "18",
    field: "day_18",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "19",
    field: "day_19",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "20",
    field: "day_20",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "21",
    field: "day_21",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "22",
    field: "day_22",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "23",
    field: "day_23",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "24",
    field: "day_24",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "25",
    field: "day_25",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "26",
    field: "day_26",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "27",
    field: "day_27",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "28",
    field: "day_28",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "29",
    field: "day_29",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "30",
    field: "day_30",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "31",
    field: "day_31",
    cellRenderer: currencyFormattedCellRenderer,
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Payment Mode Totals",
    field: "payment_mode_totals",
    filter: "agTextColumnFilter",
    cellRenderer: (params: ICellRendererParams) =>
      params.value != null ? JSON.stringify(params.value) : "",
    hide: false,
  },
  {
    headerName: "Warehouse",
    field: "warehousename",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "Warehouse ID",
    field: "warehouseid",
    filter: "agNumberColumnFilter",
    hide: true,
  },
  {
    headerName: "Outlet ID",
    field: "outletid",
    filter: "agNumberColumnFilter",
    hide: true,
  },
];
