import { SupplierListType } from "@/types/supplier";
import { ColDef } from "ag-grid-community";

export const supplierListcolumnDefs: ColDef<SupplierListType>[] = [
  {
    headerName: "Supplier ID",
    field: "supplierid",
    filter: "agNumberColumnFilter",
    hide: true,
  },
  {
    headerName: "Company Name",
    field: "companyname",
    filter: "agTextColumnFilter",
    hide: false,
  },
  {
    headerName: "Phone 1",
    field: "phone1",
    filter: "agTextColumnFilter",
    hide: false,
  },
  {
    headerName: "Cell Phone",
    field: "cellphone",
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Contact Name",
    field: "contactname",
    filter: "agTextColumnFilter",
    hide: false,
  },
  {
    headerName: "Number of Purchase",
    field: "numberofpurchase",
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Total Purchase",
    field: "totalpurchase",
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Balance Due",
    field: "balancedue",
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Open Credit",
    field: "opencredit",
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Total Sale Value",
    field: "totalsalevalue",
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Last Purchase Date",
    field: "lastpurchasedate",
    filter: "agDateColumnFilter",
    hide: false,
  },
  {
    headerName: "Last Payment Date",
    field: "lastpaymentdate",
    filter: "agDateColumnFilter",
    hide: false,
  },
  {
    headerName: "Days Since Last Purchase",
    field: "days_since_last_purchase",
    filter: "agNumberColumnFilter",
    hide: false,
  },
  {
    headerName: "Post Check Amount",
    field: "postchkamount",
    filter: "agNumberColumnFilter",
    hide: true,
  },
  {
    headerName: "Account No",
    field: "accountno",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "Terms Name",
    field: "termsname",
    filter: "agNumberColumnFilter",
    hide: true,
  },
  {
    headerName: "Phone 2",
    field: "phone2",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "City",
    field: "city",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "Email Address",
    field: "emailaddress",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "Shipping Method",
    field: "shippimgmethod",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "Discount Rate",
    field: "discountrate",
    filter: "agNumberColumnFilter",
    hide: true,
  },
  {
    headerName: "Supplier Status",
    field: "supplierstatus",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "Remarks",
    field: "remarks",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "Last Modified Date",
    field: "lastmodifieddate",
    filter: "agDateColumnFilter",
    hide: true,
  },
  {
    headerName: "Modified By",
    field: "modifiedby",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "Warehouse Name",
    field: "warehousename",
    filter: "agTextColumnFilter",
    hide: true,
  },
  {
    headerName: "Warehouse ID",
    field: "warehouseid",
    filter: "agNumberColumnFilter",
    hide: true,
  },
  {
    headerName: "Outlet ID",
    field: "outletid",
    filter: "agNumberColumnFilter",
    hide: true,
  },
];
